// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{
    /// <summary>
    /// DxfDictionary class
    /// </summary>
    public partial class DxfDictionary : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.Dictionary; } }
        public bool IsHardOwner { get; set; }
        public DxfDictionaryDuplicateRecordHandling DuplicateRecordHandling { get; set; }

        public DxfDictionary()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.IsHardOwner = false;
            this.DuplicateRecordHandling = DxfDictionaryDuplicateRecordHandling.NotApplicable;
        }
    }
}
