// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{
    /// <summary>
    /// DxfObjectPointer class
    /// </summary>
    public partial class DxfObjectPointer : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.ObjectPointer; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R14; } }
        public string AseXData { get; set; }

        public DxfObjectPointer()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.AseXData = null;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles, bool writeXData)
        {
            base.AddValuePairs(pairs, version, outputHandles, writeXData: false);
            pairs.Add(new DxfCodePair(1001, this.AseXData));
            if (writeXData)
            {
                DxfXData.AddValuePairs(XData, pairs, version, outputHandles);
            }
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 1001:
                    this.AseXData = pair.StringValue;
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }
}
