// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{
    /// <summary>
    /// DxfVbaProject class
    /// </summary>
    public partial class DxfVbaProject : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.VbaProject; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R2000; } }
        private int _hexDataSize { get; set; }
        private IList<byte[]> _hexData { get; set; }

        public DxfVbaProject()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this._hexDataSize = 0;
            this._hexData = new ListNonNull<byte[]>();
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles, bool writeXData)
        {
            base.AddValuePairs(pairs, version, outputHandles, writeXData: false);
            pairs.Add(new DxfCodePair(100, "AcDbVbaProject"));
            if ((Data?.Length ?? 0) > 0)
            {
                pairs.Add(new DxfCodePair(90, Data.Length));
                foreach (var chunk in BinaryHelpers.ChunkBytes(Data))
                {
                    pairs.Add(new DxfCodePair(310, chunk));
                }
            }

            if (writeXData)
            {
                DxfXData.AddValuePairs(XData, pairs, version, outputHandles);
            }
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 90:
                    this._hexDataSize = pair.IntegerValue;
                    break;
                case 310:
                    this._hexData.Add(pair.BinaryValue);
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }
}
