// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{
    /// <summary>
    /// DxfXRecordObject class
    /// </summary>
    public partial class DxfXRecordObject : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.XRecord; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R14; } }
        public DxfDictionaryDuplicateRecordHandling DuplicateRecordHandling { get; set; }

        public DxfXRecordObject()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.DuplicateRecordHandling = DxfDictionaryDuplicateRecordHandling.NotApplicable;
        }
    }
}
