// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Linq;
using IxMilia.Dxf.Collections;

namespace IxMilia.Dxf.Entities
{
    public enum DxfEntityType
    {
        Arc,
        ArcAlignedText,
        Attribute,
        AttributeDefinition,
        Body,
        Circle,
        DgnUnderlay,
        Dimension,
        DwfUnderlay,
        Ellipse,
        Face,
        Hatch,
        Helix,
        Image,
        Insert,
        Leader,
        Light,
        Line,
        LwPolyline,
        MLine,
        ModelerGeometry,
        MText,
        Ole2Frame,
        OleFrame,
        PdfUnderlay,
        Point,
        Polyline,
        ProxyEntity,
        Ray,
        Region,
        RText,
        Section,
        Seqend,
        Shape,
        Solid,
        Spline,
        Text,
        Tolerance,
        Trace,
        Underlay,
        Vertex,
        WipeOut,
        XLine
    }
}
