// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Linq;
using System.Collections.Generic;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Sections;
using IxMilia.Dxf.Tables;
using IxMilia.Dxf.Objects;

namespace IxMilia.Dxf
{
    public partial class DxfBlockRecord : DxfSymbolTableFlags
    {
        internal const string AcDbText = "AcDbBlockTableRecord";

        protected override DxfTableType TableType { get { return DxfTableType.BlockRecord; } }

        internal DxfPointer _layout_pointer { get; } = new DxfPointer();

        /// <summary>
        /// Minimum drawing version R2000.
        /// </summary>
        public DxfLayout Layout => _layout_pointer.Item as DxfLayout;

        /// <summary>
        /// Minimum drawing version R2007.
        /// </summary>
        public DxfUnits InsertionUnits { get; set; }

        /// <summary>
        /// Minimum drawing version R2007.
        /// </summary>
        public bool Explodability { get; set; }

        /// <summary>
        /// Minimum drawing version R2007.
        /// </summary>
        public bool Scalability { get; set; }

        /// <summary>
        /// Minimum drawing version R2000.
        /// </summary>
        private IList<byte[]> _bitmapPreviewData { get; set; }

        public IDictionary<string, DxfXDataApplicationItemCollection> XData { get; } = new DictionaryWithPredicate<string, DxfXDataApplicationItemCollection>((_key, value) => value != null);

        public DxfBlockRecord(string name)
            : this()
        {
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentException(nameof(name), $"Parameter '{nameof(name)}' must have a value.");
            }

            Name = name;
        }

        internal DxfBlockRecord()
            : base()
        {
            InsertionUnits = DxfUnits.Unitless;
            Explodability = true;
            Scalability = true;
            _bitmapPreviewData = new ListNonNull<byte[]>();
        }

        internal override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            if (version >= DxfAcadVersion.R13)
            {
                pairs.Add(new DxfCodePair(100, AcDbText));
            }

            pairs.Add(new DxfCodePair(2, Name));
            if (_layout_pointer.Handle != default(DxfHandle) && version >= DxfAcadVersion.R2000)
            {
                pairs.Add(new DxfCodePair(340, HandleString(_layout_pointer.Handle)));
            }

            if (version >= DxfAcadVersion.R2007)
            {
                pairs.Add(new DxfCodePair(70, (short)InsertionUnits));
            }

            if (version >= DxfAcadVersion.R2007)
            {
                pairs.Add(new DxfCodePair(280, BoolShort(Explodability)));
            }

            if (version >= DxfAcadVersion.R2007)
            {
                pairs.Add(new DxfCodePair(281, BoolShort(Scalability)));
            }

            if (version >= DxfAcadVersion.R2000)
            {
                pairs.AddRange(_bitmapPreviewData.Select(value => new DxfCodePair(310, value)));
            }

            DxfXData.AddValuePairs(XData, pairs, version, outputHandles);
        }

        internal static DxfBlockRecord FromBuffer(DxfCodePairBufferReader buffer)
        {
            var item = new DxfBlockRecord();
            while (buffer.ItemsRemain)
            {
                var pair = buffer.Peek();
                if (pair.Code == 0)
                {
                    break;
                }

                buffer.Advance();
                switch (pair.Code)
                {
                    case DxfCodePairGroup.GroupCodeNumber:
                        var groupName = DxfCodePairGroup.GetGroupName(pair.StringValue);
                        item.ExtensionDataGroups.Add(DxfCodePairGroup.FromBuffer(buffer, groupName));
                        break;
                    case (int)DxfXDataType.ApplicationName:
                        DxfXData.PopulateFromBuffer(buffer, item.XData, pair.StringValue);
                        break;
                    default:
                        item.ApplyCodePair(pair);
                        break;
                }
            }

            return item;
        }

        private void ApplyCodePair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 340:
                    _layout_pointer.Handle = HandleString(pair.StringValue);
                    break;
                case 70:
                    InsertionUnits = (DxfUnits)pair.ShortValue;
                    break;
                case 280:
                    Explodability = BoolShort(pair.ShortValue);
                    break;
                case 281:
                    Scalability = BoolShort(pair.ShortValue);
                    break;
                case 310:
                    _bitmapPreviewData.Add(pair.BinaryValue);
                    break;
                default:
                    TrySetPair(pair);
                    break;
            }
        }

        public DxfBlockRecord Clone()
        {
            return (DxfBlockRecord)this.MemberwiseClone();
        }
    }
}
