// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Linq;
using System.Collections.Generic;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Sections;
using IxMilia.Dxf.Tables;

namespace IxMilia.Dxf
{
    public partial class DxfLayer : DxfSymbolTableFlags
    {
        internal const string AcDbText = "AcDbLayerTableRecord";

        protected override DxfTableType TableType { get { return DxfTableType.Layer; } }


        public DxfColor Color { get; set; }

        public string LineTypeName { get; set; }

        /// <summary>
        /// Minimum drawing version R2000.
        /// </summary>
        public bool IsLayerPlotted { get; set; }

        /// <summary>
        /// Minimum drawing version R2000.
        /// </summary>
        public DxfLineWeight LineWeight { get; set; }

        /// <summary>
        /// Minimum drawing version R2000.
        /// </summary>
        public DxfHandle PlotStylePointer { get; set; }

        /// <summary>
        /// Minimum drawing version R2007.
        /// </summary>
        public DxfHandle MaterialHandle { get; set; }

        public IDictionary<string, DxfXDataApplicationItemCollection> XData { get; } = new DictionaryWithPredicate<string, DxfXDataApplicationItemCollection>((_key, value) => value != null);

        public DxfLayer(string name)
            : this()
        {
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentException(nameof(name), $"Parameter '{nameof(name)}' must have a value.");
            }

            Name = name;
        }

        internal DxfLayer()
            : base()
        {
            Color = DxfColor.FromIndex(7);
            LineTypeName = "CONTINUOUS";
            IsLayerPlotted = true;
            LineWeight = new DxfLineWeight();
            PlotStylePointer = default(DxfHandle);
            MaterialHandle = default(DxfHandle);
        }

        internal override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            if (version >= DxfAcadVersion.R13)
            {
                pairs.Add(new DxfCodePair(100, AcDbText));
            }

            pairs.Add(new DxfCodePair(2, Name));
            pairs.Add(new DxfCodePair(70, (short)StandardFlags));
            pairs.Add(new DxfCodePair(62, GetWritableColorValue(Color)));
            pairs.Add(new DxfCodePair(6, GetWritableLineTypeName(LineTypeName)));
            if (version >= DxfAcadVersion.R2000)
            {
                pairs.Add(new DxfCodePair(290, IsLayerPlotted));
            }

            if (version >= DxfAcadVersion.R2000)
            {
                pairs.Add(new DxfCodePair(370, DxfLineWeight.GetRawValue(LineWeight)));
            }

            if (version >= DxfAcadVersion.R2000)
            {
                pairs.Add(new DxfCodePair(390, HandleString(PlotStylePointer)));
            }

            if (MaterialHandle != default(DxfHandle) && version >= DxfAcadVersion.R2007)
            {
                pairs.Add(new DxfCodePair(347, HandleString(MaterialHandle)));
            }

            DxfXData.AddValuePairs(XData, pairs, version, outputHandles);
        }

        internal static DxfLayer FromBuffer(DxfCodePairBufferReader buffer)
        {
            var item = new DxfLayer();
            while (buffer.ItemsRemain)
            {
                var pair = buffer.Peek();
                if (pair.Code == 0)
                {
                    break;
                }

                buffer.Advance();
                switch (pair.Code)
                {
                    case DxfCodePairGroup.GroupCodeNumber:
                        var groupName = DxfCodePairGroup.GetGroupName(pair.StringValue);
                        item.ExtensionDataGroups.Add(DxfCodePairGroup.FromBuffer(buffer, groupName));
                        break;
                    case (int)DxfXDataType.ApplicationName:
                        DxfXData.PopulateFromBuffer(buffer, item.XData, pair.StringValue);
                        break;
                    default:
                        item.ApplyCodePair(pair);
                        break;
                }
            }

            return item;
        }

        private void ApplyCodePair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 70:
                    StandardFlags = (int)pair.ShortValue;
                    break;
                case 62:
                    Color = ReadColorValue(pair.ShortValue);
                    break;
                case 6:
                    LineTypeName = pair.StringValue;
                    break;
                case 290:
                    IsLayerPlotted = pair.BoolValue;
                    break;
                case 370:
                    LineWeight = DxfLineWeight.FromRawValue(pair.ShortValue);
                    break;
                case 390:
                    PlotStylePointer = HandleString(pair.StringValue);
                    break;
                case 347:
                    MaterialHandle = HandleString(pair.StringValue);
                    break;
                default:
                    TrySetPair(pair);
                    break;
            }
        }

        public DxfLayer Clone()
        {
            return (DxfLayer)this.MemberwiseClone();
        }
    }
}
